from flask import Flask, request, jsonify
import random


"""
This code is not finished.
Waiting for y_pred value, generated by DS-unit4.
In this code, temporarily, y_pred is taken as random value.
"""


app = Flask(__name__)

@app.route('/', methods=["GET"])
def root():
    return jsonify("Hello user")


@app.route('/user/<username>', methods=["GET"])
def user(username):
    # return "Hello user"
    object_to_return = {
        "username":username,
        "num_tweets":random.randint(0, 9),
        "something_that_shouldnt_work": p
    }
    return object_to_return # jsonify(object_to_return)


@app.route('/predict', methods=["POST"])
def predict():

    
    ###### getting the data from client through parameters
    # note: make sure to be sending data from client in PARAMS not BODY
    params = request.args
    print("params?: ", params)
    num_bedrooms = params.get("bedrooms")
    num_bathrooms = params.get("bathrooms")


    ###### getting the data from client through *body* in json format
    # note: make sure to be sending data from client in BODY not PARAMS
    # data_as_dictionary = request.get_json(force=True)
    # print("data as dictionary: ", data_as_dictionary)
    # num_bedrooms = data_as_dictionary["bedrooms"]
    # num_bathrooms = data_as_dictionary["bathrooms"]
    

    # someone makes a model, and I can use that model through a function
    # price = predict_with_params(num_bedrooms, num_bathrooms,x,y,z....)
    y_pred = random.randint(20, 300)
    res = {
        "status": "success",
        "predicted_price": y_pred
    }

    return jsonify(res)

